kind: Deployment
apiVersion: apps/v1
metadata:
  name: app02-fdevsec
spec:
  template:
    metadata:
      labels:
        app: app02-fdevsec
    spec:
      containers:
      - name: app02-fdevsec
        image: 363412468025.dkr.ecr.us-east-2.amazonaws.com/app02-fdevsec:latest
  selector:
    matchLabels:
      app: app02-fdevsec
---
kind: Service
apiVersion: v1
metadata:
  name: app02-fdevsec
spec:
  type: LoadBalancer
  selector:
    app: app02-fdevsec
  ports:
  - name: http
    port: 5006
    targetPort: 3001
